// Code generated by MockGen. DO NOT EDIT.
// Source: internal/eval/usecase/evaluate/main.go
//
// Generated by this command:
//
//	mockgen -source=internal/eval/usecase/evaluate/main.go -destination=internal/eval/usecase/evaluate/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/squeakycheese75/open-incentives/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockActionApplier is a mock of ActionApplier interface.
type MockActionApplier struct {
	ctrl     *gomock.Controller
	recorder *MockActionApplierMockRecorder
	isgomock struct{}
}

// MockActionApplierMockRecorder is the mock recorder for MockActionApplier.
type MockActionApplierMockRecorder struct {
	mock *MockActionApplier
}

// NewMockActionApplier creates a new mock instance.
func NewMockActionApplier(ctrl *gomock.Controller) *MockActionApplier {
	mock := &MockActionApplier{ctrl: ctrl}
	mock.recorder = &MockActionApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionApplier) EXPECT() *MockActionApplierMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockActionApplier) Apply(cart domain.Cart, matches []domain.MatchedAction) (domain.EvaluateUsecaseOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", cart, matches)
	ret0, _ := ret[0].(domain.EvaluateUsecaseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockActionApplierMockRecorder) Apply(cart, matches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockActionApplier)(nil).Apply), cart, matches)
}

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
	isgomock struct{}
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockRuntime) Evaluate(ctx context.Context, req domain.RuleEvaluationRequest) (domain.RuleEvaluationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, req)
	ret0, _ := ret[0].(domain.RuleEvaluationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockRuntimeMockRecorder) Evaluate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockRuntime)(nil).Evaluate), ctx, req)
}

// MockScopedCampaignStore is a mock of ScopedCampaignStore interface.
type MockScopedCampaignStore struct {
	ctrl     *gomock.Controller
	recorder *MockScopedCampaignStoreMockRecorder
	isgomock struct{}
}

// MockScopedCampaignStoreMockRecorder is the mock recorder for MockScopedCampaignStore.
type MockScopedCampaignStoreMockRecorder struct {
	mock *MockScopedCampaignStore
}

// NewMockScopedCampaignStore creates a new mock instance.
func NewMockScopedCampaignStore(ctrl *gomock.Controller) *MockScopedCampaignStore {
	mock := &MockScopedCampaignStore{ctrl: ctrl}
	mock.recorder = &MockScopedCampaignStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopedCampaignStore) EXPECT() *MockScopedCampaignStoreMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockScopedCampaignStore) List(ctx context.Context, projectID int64) ([]domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, projectID)
	ret0, _ := ret[0].([]domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockScopedCampaignStoreMockRecorder) List(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScopedCampaignStore)(nil).List), ctx, projectID)
}
