// Code generated by MockGen. DO NOT EDIT.
// Source: internal/admin/usecase/project_list/main.go
//
// Generated by this command:
//
//	mockgen -source=internal/admin/usecase/project_list/main.go -destination=internal/admin/usecase/project_list/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/squeakycheese75/open-incentives/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScopedProjectStore is a mock of ScopedProjectStore interface.
type MockScopedProjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockScopedProjectStoreMockRecorder
	isgomock struct{}
}

// MockScopedProjectStoreMockRecorder is the mock recorder for MockScopedProjectStore.
type MockScopedProjectStoreMockRecorder struct {
	mock *MockScopedProjectStore
}

// NewMockScopedProjectStore creates a new mock instance.
func NewMockScopedProjectStore(ctrl *gomock.Controller) *MockScopedProjectStore {
	mock := &MockScopedProjectStore{ctrl: ctrl}
	mock.recorder = &MockScopedProjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopedProjectStore) EXPECT() *MockScopedProjectStoreMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockScopedProjectStore) List(ctx context.Context) ([]domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockScopedProjectStoreMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScopedProjectStore)(nil).List), ctx)
}
