// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/squeakycheese75/open-incentives/internal/store (interfaces: CampaignStore,ScopedCampaignStore)
//
// Generated by this command:
//
//	mockgen -destination=internal/store/mocks/campaign_store.go -package=mocks github.com/squeakycheese75/open-incentives/internal/store CampaignStore,ScopedCampaignStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/squeakycheese75/open-incentives/internal/domain"
	store "github.com/squeakycheese75/open-incentives/internal/store"
	gomock "go.uber.org/mock/gomock"
)

// MockCampaignStore is a mock of CampaignStore interface.
type MockCampaignStore struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignStoreMockRecorder
	isgomock struct{}
}

// MockCampaignStoreMockRecorder is the mock recorder for MockCampaignStore.
type MockCampaignStoreMockRecorder struct {
	mock *MockCampaignStore
}

// NewMockCampaignStore creates a new mock instance.
func NewMockCampaignStore(ctrl *gomock.Controller) *MockCampaignStore {
	mock := &MockCampaignStore{ctrl: ctrl}
	mock.recorder = &MockCampaignStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignStore) EXPECT() *MockCampaignStoreMockRecorder {
	return m.recorder
}

// Scope mocks base method.
func (m *MockCampaignStore) Scope(orgID int64) store.ScopedCampaignStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scope", orgID)
	ret0, _ := ret[0].(store.ScopedCampaignStore)
	return ret0
}

// Scope indicates an expected call of Scope.
func (mr *MockCampaignStoreMockRecorder) Scope(orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scope", reflect.TypeOf((*MockCampaignStore)(nil).Scope), orgID)
}

// MockScopedCampaignStore is a mock of ScopedCampaignStore interface.
type MockScopedCampaignStore struct {
	ctrl     *gomock.Controller
	recorder *MockScopedCampaignStoreMockRecorder
	isgomock struct{}
}

// MockScopedCampaignStoreMockRecorder is the mock recorder for MockScopedCampaignStore.
type MockScopedCampaignStoreMockRecorder struct {
	mock *MockScopedCampaignStore
}

// NewMockScopedCampaignStore creates a new mock instance.
func NewMockScopedCampaignStore(ctrl *gomock.Controller) *MockScopedCampaignStore {
	mock := &MockScopedCampaignStore{ctrl: ctrl}
	mock.recorder = &MockScopedCampaignStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopedCampaignStore) EXPECT() *MockScopedCampaignStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScopedCampaignStore) Create(ctx context.Context, campaign domain.Campaign) (domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, campaign)
	ret0, _ := ret[0].(domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockScopedCampaignStoreMockRecorder) Create(ctx, campaign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScopedCampaignStore)(nil).Create), ctx, campaign)
}

// Find mocks base method.
func (m *MockScopedCampaignStore) Find(ctx context.Context, campaignPublicID string, projectID int64) (domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, campaignPublicID, projectID)
	ret0, _ := ret[0].(domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockScopedCampaignStoreMockRecorder) Find(ctx, campaignPublicID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockScopedCampaignStore)(nil).Find), ctx, campaignPublicID, projectID)
}

// List mocks base method.
func (m *MockScopedCampaignStore) List(ctx context.Context, projectID int64) ([]domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, projectID)
	ret0, _ := ret[0].([]domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockScopedCampaignStoreMockRecorder) List(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScopedCampaignStore)(nil).List), ctx, projectID)
}
