// Code generated by MockGen. DO NOT EDIT.
// Source: internal/admin/usecase/campaign_update/main.go
//
// Generated by this command:
//
//	mockgen -source=internal/admin/usecase/campaign_update/main.go -destination=internal/admin/usecase/campaign_update/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/squeakycheese75/open-incentives/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScopedProjectStore is a mock of ScopedProjectStore interface.
type MockScopedProjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockScopedProjectStoreMockRecorder
	isgomock struct{}
}

// MockScopedProjectStoreMockRecorder is the mock recorder for MockScopedProjectStore.
type MockScopedProjectStoreMockRecorder struct {
	mock *MockScopedProjectStore
}

// NewMockScopedProjectStore creates a new mock instance.
func NewMockScopedProjectStore(ctrl *gomock.Controller) *MockScopedProjectStore {
	mock := &MockScopedProjectStore{ctrl: ctrl}
	mock.recorder = &MockScopedProjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopedProjectStore) EXPECT() *MockScopedProjectStoreMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockScopedProjectStore) Find(ctx context.Context, publicID string) (domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, publicID)
	ret0, _ := ret[0].(domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockScopedProjectStoreMockRecorder) Find(ctx, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockScopedProjectStore)(nil).Find), ctx, publicID)
}

// MockScopedCampaignStore is a mock of ScopedCampaignStore interface.
type MockScopedCampaignStore struct {
	ctrl     *gomock.Controller
	recorder *MockScopedCampaignStoreMockRecorder
	isgomock struct{}
}

// MockScopedCampaignStoreMockRecorder is the mock recorder for MockScopedCampaignStore.
type MockScopedCampaignStoreMockRecorder struct {
	mock *MockScopedCampaignStore
}

// NewMockScopedCampaignStore creates a new mock instance.
func NewMockScopedCampaignStore(ctrl *gomock.Controller) *MockScopedCampaignStore {
	mock := &MockScopedCampaignStore{ctrl: ctrl}
	mock.recorder = &MockScopedCampaignStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopedCampaignStore) EXPECT() *MockScopedCampaignStoreMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockScopedCampaignStore) Update(ctx context.Context, campaignPublicID string, projectID int64, update domain.Campaign) (domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, campaignPublicID, projectID, update)
	ret0, _ := ret[0].(domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockScopedCampaignStoreMockRecorder) Update(ctx, campaignPublicID, projectID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScopedCampaignStore)(nil).Update), ctx, campaignPublicID, projectID, update)
}
