// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlitedb

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID         int64
	PublicID   string
	OrgID      int64
	ProjectID  int64
	Name       string
	KeyHash    string
	Prefix     string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
	LastUsedAt sql.NullTime
	RevokedAt  sql.NullTime
}

type Campaign struct {
	ID        int64
	PublicID  string
	OrgID     int64
	ProjectID int64
	Name      string
	Status    string
	Rules     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Organization struct {
	ID        int64
	PublicID  string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Project struct {
	ID        int64
	PublicID  string
	OrgID     int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID           int64
	PublicID     string
	OrgID        int64
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
