// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlitedb

import (
	"database/sql"
)

type ApiKey struct {
	ID         int64
	PublicID   string
	OrgID      int64
	ProjectID  int64
	Name       string
	KeyHash    string
	Prefix     string
	Status     string
	CreatedAt  string
	UpdatedAt  string
	LastUsedAt sql.NullString
	RevokedAt  sql.NullString
}

type Campaign struct {
	ID        int64
	PublicID  string
	OrgID     int64
	ProjectID int64
	Name      string
	Status    string
	Rule      []byte
	CreatedAt string
	UpdatedAt string
	DeletedAt sql.NullString
}

type Organization struct {
	ID        int64
	PublicID  string
	Name      string
	CreatedAt string
	UpdatedAt string
	DeletedAt sql.NullString
}

type Project struct {
	ID        int64
	PublicID  string
	OrgID     int64
	Name      string
	CreatedAt string
	UpdatedAt string
	DeletedAt sql.NullString
}
