// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (name, public_id, status, rules, project_id, org_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, public_id, name, status, rules, project_id, org_id, created_at, updated_at
`

type CreateCampaignParams struct {
	Name      string
	PublicID  string
	Status    string
	Rules     []byte
	ProjectID int64
	OrgID     int64
}

type CreateCampaignRow struct {
	ID        int64
	PublicID  string
	Name      string
	Status    string
	Rules     []byte
	ProjectID int64
	OrgID     int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (CreateCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, createCampaign,
		arg.Name,
		arg.PublicID,
		arg.Status,
		arg.Rules,
		arg.ProjectID,
		arg.OrgID,
	)
	var i CreateCampaignRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Status,
		&i.Rules,
		&i.ProjectID,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (public_id, org_id, name)
VALUES (?, ?, ?)
RETURNING id, public_id, org_id, name, created_at, updated_at
`

type CreateProjectParams struct {
	PublicID string
	OrgID    int64
	Name     string
}

type CreateProjectRow struct {
	ID        int64
	PublicID  string
	OrgID     int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.PublicID, arg.OrgID, arg.Name)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectAPIKey = `-- name: CreateProjectAPIKey :one
INSERT INTO api_keys (name, public_id, org_id, project_id, key_hash, prefix, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, public_id, org_id,  project_id, name, key_hash, prefix, status, created_at, updated_at
`

type CreateProjectAPIKeyParams struct {
	Name      string
	PublicID  string
	OrgID     int64
	ProjectID int64
	KeyHash   string
	Prefix    string
	Status    string
}

type CreateProjectAPIKeyRow struct {
	ID        int64
	PublicID  string
	OrgID     int64
	ProjectID int64
	Name      string
	KeyHash   string
	Prefix    string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateProjectAPIKey(ctx context.Context, arg CreateProjectAPIKeyParams) (CreateProjectAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, createProjectAPIKey,
		arg.Name,
		arg.PublicID,
		arg.OrgID,
		arg.ProjectID,
		arg.KeyHash,
		arg.Prefix,
		arg.Status,
	)
	var i CreateProjectAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
UPDATE campaigns
SET deleted_at = CURRENT_TIMESTAMP
WHERE public_id = ?
AND project_id = ?
AND org_id = ?
`

type DeleteCampaignParams struct {
	PublicID  string
	ProjectID int64
	OrgID     int64
}

func (q *Queries) DeleteCampaign(ctx context.Context, arg DeleteCampaignParams) error {
	_, err := q.db.ExecContext(ctx, deleteCampaign, arg.PublicID, arg.ProjectID, arg.OrgID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE projects
SET deleted_at = CURRENT_TIMESTAMP
WHERE public_id = ?
AND org_id = ?
AND deleted_at IS NULL
`

type DeleteProjectParams struct {
	PublicID string
	OrgID    int64
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteProject, arg.PublicID, arg.OrgID)
	return err
}

const getActiveAPIKeyByPublicID = `-- name: GetActiveAPIKeyByPublicID :one
SELECT
    ak.id,
    ak.public_id,
    ak.key_hash,
    ak.project_id,
    p.org_id
FROM api_keys ak
JOIN projects p ON p.id = ak.project_id
WHERE ak.public_id = ?
  AND ak.revoked_at IS NULL
  AND ak.deleted_at IS NULL
  AND p.deleted_at IS NULL
`

type GetActiveAPIKeyByPublicIDRow struct {
	ID        int64
	PublicID  string
	KeyHash   string
	ProjectID int64
	OrgID     int64
}

func (q *Queries) GetActiveAPIKeyByPublicID(ctx context.Context, publicID string) (GetActiveAPIKeyByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveAPIKeyByPublicID, publicID)
	var i GetActiveAPIKeyByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.KeyHash,
		&i.ProjectID,
		&i.OrgID,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, public_id, name, status, rules, created_at, updated_at
FROM campaigns
WHERE public_id = ?
AND org_id = ?
AND project_id = ?
AND deleted_at IS NULL
`

type GetCampaignParams struct {
	PublicID  string
	OrgID     int64
	ProjectID int64
}

type GetCampaignRow struct {
	ID        int64
	PublicID  string
	Name      string
	Status    string
	Rules     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetCampaign(ctx context.Context, arg GetCampaignParams) (GetCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, getCampaign, arg.PublicID, arg.OrgID, arg.ProjectID)
	var i GetCampaignRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Status,
		&i.Rules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgByPublicID = `-- name: GetOrgByPublicID :one
SELECT id, public_id, name
FROM organizations
WHERE public_id = ?
AND deleted_at IS NULL
`

type GetOrgByPublicIDRow struct {
	ID       int64
	PublicID string
	Name     string
}

func (q *Queries) GetOrgByPublicID(ctx context.Context, publicID string) (GetOrgByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgByPublicID, publicID)
	var i GetOrgByPublicIDRow
	err := row.Scan(&i.ID, &i.PublicID, &i.Name)
	return i, err
}

const getProjectByPublicID = `-- name: GetProjectByPublicID :one
SELECT id, public_id, org_id, name, created_at, updated_at
FROM projects
WHERE public_id = ?
AND org_id = ?
AND deleted_at IS NULL
`

type GetProjectByPublicIDParams struct {
	PublicID string
	OrgID    int64
}

type GetProjectByPublicIDRow struct {
	ID        int64
	PublicID  string
	OrgID     int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetProjectByPublicID(ctx context.Context, arg GetProjectByPublicIDParams) (GetProjectByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByPublicID, arg.PublicID, arg.OrgID)
	var i GetProjectByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailAndOrg = `-- name: GetUserByEmailAndOrg :one
SELECT id, public_id, email, org_id, password_hash, role
FROM users
WHERE email = ?
AND org_id = ?
AND deleted_at IS NULL
`

type GetUserByEmailAndOrgParams struct {
	Email string
	OrgID int64
}

type GetUserByEmailAndOrgRow struct {
	ID           int64
	PublicID     string
	Email        string
	OrgID        int64
	PasswordHash string
	Role         string
}

func (q *Queries) GetUserByEmailAndOrg(ctx context.Context, arg GetUserByEmailAndOrgParams) (GetUserByEmailAndOrgRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailAndOrg, arg.Email, arg.OrgID)
	var i GetUserByEmailAndOrgRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.OrgID,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const listAPIKeysByProject = `-- name: ListAPIKeysByProject :many
SELECT id, public_id, org_id, project_id, name, prefix, status, created_at, updated_at, last_used_at, revoked_at
FROM api_keys
WHERE org_id = ?
AND project_id = ?
AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListAPIKeysByProjectParams struct {
	OrgID     int64
	ProjectID int64
}

type ListAPIKeysByProjectRow struct {
	ID         int64
	PublicID   string
	OrgID      int64
	ProjectID  int64
	Name       string
	Prefix     string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastUsedAt sql.NullTime
	RevokedAt  sql.NullTime
}

func (q *Queries) ListAPIKeysByProject(ctx context.Context, arg ListAPIKeysByProjectParams) ([]ListAPIKeysByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByProject, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByProjectRow
	for rows.Next() {
		var i ListAPIKeysByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.Prefix,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveCampaignsByProject = `-- name: ListActiveCampaignsByProject :many
SELECT id, public_id, name, status, rules, created_at, updated_at
FROM campaigns
WHERE org_id = ?
AND project_id = ?
AND status = 'active'
AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListActiveCampaignsByProjectParams struct {
	OrgID     int64
	ProjectID int64
}

type ListActiveCampaignsByProjectRow struct {
	ID        int64
	PublicID  string
	Name      string
	Status    string
	Rules     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListActiveCampaignsByProject(ctx context.Context, arg ListActiveCampaignsByProjectParams) ([]ListActiveCampaignsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCampaignsByProject, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCampaignsByProjectRow
	for rows.Next() {
		var i ListActiveCampaignsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Status,
			&i.Rules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOrg = `-- name: ListProjectsByOrg :many
SELECT id, public_id, org_id, name, created_at, updated_at
FROM projects
WHERE org_id = ?
AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListProjectsByOrgRow struct {
	ID        int64
	PublicID  string
	OrgID     int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListProjectsByOrg(ctx context.Context, orgID int64) ([]ListProjectsByOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByOrgRow
	for rows.Next() {
		var i ListProjectsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET status = 'revoked', revoked_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE public_id = ?
AND project_id = ?
AND org_id = ?
AND deleted_at IS NULL
AND status = 'active'
RETURNING id, public_id, org_id, project_id, name, prefix, status, created_at, updated_at, last_used_at, revoked_at
`

type RevokeAPIKeyParams struct {
	PublicID  string
	ProjectID int64
	OrgID     int64
}

type RevokeAPIKeyRow struct {
	ID         int64
	PublicID   string
	OrgID      int64
	ProjectID  int64
	Name       string
	Prefix     string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastUsedAt sql.NullTime
	RevokedAt  sql.NullTime
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (RevokeAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, revokeAPIKey, arg.PublicID, arg.ProjectID, arg.OrgID)
	var i RevokeAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET
    name = ?,
    status = ?,
    rules = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE public_id = ?
AND project_id = ?
AND org_id = ?
AND deleted_at IS NULL
RETURNING id, public_id, name, status, rules, created_at, updated_at
`

type UpdateCampaignParams struct {
	Name      string
	Status    string
	Rules     []byte
	PublicID  string
	ProjectID int64
	OrgID     int64
}

type UpdateCampaignRow struct {
	ID        int64
	PublicID  string
	Name      string
	Status    string
	Rules     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (UpdateCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, updateCampaign,
		arg.Name,
		arg.Status,
		arg.Rules,
		arg.PublicID,
		arg.ProjectID,
		arg.OrgID,
	)
	var i UpdateCampaignRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Status,
		&i.Rules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = ?, updated_at = CURRENT_TIMESTAMP
WHERE public_id = ?
AND org_id = ?
AND deleted_at IS NULL
RETURNING id, public_id, org_id, name, created_at, updated_at
`

type UpdateProjectParams struct {
	Name     string
	PublicID string
	OrgID    int64
}

type UpdateProjectRow struct {
	ID        int64
	PublicID  string
	OrgID     int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.PublicID, arg.OrgID)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
