// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sqlitedb

import (
	"context"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (name, public_id, status, rule)
VALUES (?, ?, ?, ?)
RETURNING id, public_id, name, status, rule, created_at, updated_at
`

type CreateCampaignParams struct {
	Name     string
	PublicID string
	Status   string
	Rule     []byte
}

type CreateCampaignRow struct {
	ID        int64
	PublicID  string
	Name      string
	Status    string
	Rule      []byte
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (CreateCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, createCampaign,
		arg.Name,
		arg.PublicID,
		arg.Status,
		arg.Rule,
	)
	var i CreateCampaignRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Status,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
UPDATE campaigns
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) DeleteCampaign(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCampaign, id)
	return err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, public_id, name, status, rule, created_at, updated_at
FROM campaigns
WHERE public_id = ?
AND deleted_at IS NULL
`

type GetCampaignRow struct {
	ID        int64
	PublicID  string
	Name      string
	Status    string
	Rule      []byte
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) GetCampaign(ctx context.Context, publicID string) (GetCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, getCampaign, publicID)
	var i GetCampaignRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Status,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCampaigns = `-- name: ListActiveCampaigns :many
SELECT id, public_id, name, status, rule, created_at, updated_at
FROM campaigns
WHERE status = 'active'
AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListActiveCampaignsRow struct {
	ID        int64
	PublicID  string
	Name      string
	Status    string
	Rule      []byte
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) ListActiveCampaigns(ctx context.Context) ([]ListActiveCampaignsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCampaignsRow
	for rows.Next() {
		var i ListActiveCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Status,
			&i.Rule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, public_id, name, status, rule, created_at, updated_at
FROM campaigns
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

type ListCampaignsRow struct {
	ID        int64
	PublicID  string
	Name      string
	Status    string
	Rule      []byte
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) ListCampaigns(ctx context.Context) ([]ListCampaignsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsRow
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Status,
			&i.Rule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET
    public_id = ?,
    name = ?,
    status = ?,
    rule = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
AND deleted_at IS NULL
RETURNING id, public_id, name, status, rule, created_at, updated_at
`

type UpdateCampaignParams struct {
	PublicID string
	Name     string
	Status   string
	Rule     []byte
	ID       int64
}

type UpdateCampaignRow struct {
	ID        int64
	PublicID  string
	Name      string
	Status    string
	Rule      []byte
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (UpdateCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, updateCampaign,
		arg.PublicID,
		arg.Name,
		arg.Status,
		arg.Rule,
		arg.ID,
	)
	var i UpdateCampaignRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Status,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
