// Code generated by MockGen. DO NOT EDIT.
// Source: internal/admin/usecase/project_create/main.go
//
// Generated by this command:
//
//	mockgen -source=internal/admin/usecase/project_create/main.go -destination=internal/admin/usecase/project_create/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/squeakycheese75/open-incentives/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPublicIDGenerator is a mock of PublicIDGenerator interface.
type MockPublicIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockPublicIDGeneratorMockRecorder
	isgomock struct{}
}

// MockPublicIDGeneratorMockRecorder is the mock recorder for MockPublicIDGenerator.
type MockPublicIDGeneratorMockRecorder struct {
	mock *MockPublicIDGenerator
}

// NewMockPublicIDGenerator creates a new mock instance.
func NewMockPublicIDGenerator(ctrl *gomock.Controller) *MockPublicIDGenerator {
	mock := &MockPublicIDGenerator{ctrl: ctrl}
	mock.recorder = &MockPublicIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicIDGenerator) EXPECT() *MockPublicIDGeneratorMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockPublicIDGenerator) New(prefix string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", prefix)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockPublicIDGeneratorMockRecorder) New(prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockPublicIDGenerator)(nil).New), prefix)
}

// MockScopedProjectStore is a mock of ScopedProjectStore interface.
type MockScopedProjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockScopedProjectStoreMockRecorder
	isgomock struct{}
}

// MockScopedProjectStoreMockRecorder is the mock recorder for MockScopedProjectStore.
type MockScopedProjectStoreMockRecorder struct {
	mock *MockScopedProjectStore
}

// NewMockScopedProjectStore creates a new mock instance.
func NewMockScopedProjectStore(ctrl *gomock.Controller) *MockScopedProjectStore {
	mock := &MockScopedProjectStore{ctrl: ctrl}
	mock.recorder = &MockScopedProjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopedProjectStore) EXPECT() *MockScopedProjectStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScopedProjectStore) Create(ctx context.Context, project domain.Project) (domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, project)
	ret0, _ := ret[0].(domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockScopedProjectStoreMockRecorder) Create(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScopedProjectStore)(nil).Create), ctx, project)
}
