// Code generated by MockGen. DO NOT EDIT.
// Source: internal/admin/usecase/apikey_revoke/main.go
//
// Generated by this command:
//
//	mockgen -source=internal/admin/usecase/apikey_revoke/main.go -destination=internal/admin/usecase/apikey_revoke/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/squeakycheese75/open-incentives/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScopedProjectStore is a mock of ScopedProjectStore interface.
type MockScopedProjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockScopedProjectStoreMockRecorder
	isgomock struct{}
}

// MockScopedProjectStoreMockRecorder is the mock recorder for MockScopedProjectStore.
type MockScopedProjectStoreMockRecorder struct {
	mock *MockScopedProjectStore
}

// NewMockScopedProjectStore creates a new mock instance.
func NewMockScopedProjectStore(ctrl *gomock.Controller) *MockScopedProjectStore {
	mock := &MockScopedProjectStore{ctrl: ctrl}
	mock.recorder = &MockScopedProjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopedProjectStore) EXPECT() *MockScopedProjectStoreMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockScopedProjectStore) Find(ctx context.Context, publicID string) (domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, publicID)
	ret0, _ := ret[0].(domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockScopedProjectStoreMockRecorder) Find(ctx, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockScopedProjectStore)(nil).Find), ctx, publicID)
}

// MockScopedAPIKeyStore is a mock of ScopedAPIKeyStore interface.
type MockScopedAPIKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockScopedAPIKeyStoreMockRecorder
	isgomock struct{}
}

// MockScopedAPIKeyStoreMockRecorder is the mock recorder for MockScopedAPIKeyStore.
type MockScopedAPIKeyStoreMockRecorder struct {
	mock *MockScopedAPIKeyStore
}

// NewMockScopedAPIKeyStore creates a new mock instance.
func NewMockScopedAPIKeyStore(ctrl *gomock.Controller) *MockScopedAPIKeyStore {
	mock := &MockScopedAPIKeyStore{ctrl: ctrl}
	mock.recorder = &MockScopedAPIKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopedAPIKeyStore) EXPECT() *MockScopedAPIKeyStoreMockRecorder {
	return m.recorder
}

// Revoke mocks base method.
func (m *MockScopedAPIKeyStore) Revoke(ctx context.Context, apiKeyPublicID string, projectID int64) (domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, apiKeyPublicID, projectID)
	ret0, _ := ret[0].(domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockScopedAPIKeyStoreMockRecorder) Revoke(ctx, apiKeyPublicID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockScopedAPIKeyStore)(nil).Revoke), ctx, apiKeyPublicID, projectID)
}
