// Code generated by MockGen. DO NOT EDIT.
// Source: internal/admin/usecase/project_update/main.go
//
// Generated by this command:
//
//	mockgen -source=internal/admin/usecase/project_update/main.go -destination=internal/admin/usecase/project_update/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/squeakycheese75/open-incentives/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScopedProjectStore is a mock of ScopedProjectStore interface.
type MockScopedProjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockScopedProjectStoreMockRecorder
	isgomock struct{}
}

// MockScopedProjectStoreMockRecorder is the mock recorder for MockScopedProjectStore.
type MockScopedProjectStoreMockRecorder struct {
	mock *MockScopedProjectStore
}

// NewMockScopedProjectStore creates a new mock instance.
func NewMockScopedProjectStore(ctrl *gomock.Controller) *MockScopedProjectStore {
	mock := &MockScopedProjectStore{ctrl: ctrl}
	mock.recorder = &MockScopedProjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopedProjectStore) EXPECT() *MockScopedProjectStoreMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockScopedProjectStore) Update(ctx context.Context, publicID, name string) (domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, publicID, name)
	ret0, _ := ret[0].(domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockScopedProjectStoreMockRecorder) Update(ctx, publicID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScopedProjectStore)(nil).Update), ctx, publicID, name)
}
